%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-swri-roscpp
Version:        3.8.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS swri_roscpp package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-diagnostic-msgs
Requires:       ros-kilted-diagnostic-updater
Requires:       ros-kilted-marti-common-msgs
Requires:       ros-kilted-nav-msgs
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rosidl-default-runtime
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-diagnostic-msgs
BuildRequires:  ros-kilted-diagnostic-updater
BuildRequires:  ros-kilted-marti-common-msgs
BuildRequires:  ros-kilted-nav-msgs
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  ros-kilted-rosidl-cmake
BuildRequires:  ros-kilted-rosidl-default-generators
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-ros-workspace
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-kilted-rosidl-interface-packages(member)

%if 0%{?with_tests}
BuildRequires:  gtest-devel
BuildRequires:  ros-kilted-ament-cmake-gtest
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-kilted-rosidl-interface-packages(all)
%endif

%description
A package that extends rclcpp with some commonly used functionality to reduce
boilerplate code.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Jun 10 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.4-1
- Autogenerated by Bloom

* Tue Jun 03 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.3-1
- Autogenerated by Bloom

* Mon Jun 02 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.2-1
- Autogenerated by Bloom

* Thu May 29 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.1-1
- Autogenerated by Bloom

* Tue May 27 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.0-1
- Autogenerated by Bloom

* Tue May 20 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.5-1
- Autogenerated by Bloom

* Tue May 20 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.4-3
- Autogenerated by Bloom

* Tue Apr 22 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.4-2
- Autogenerated by Bloom

* Mon Apr 14 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.4-1
- Autogenerated by Bloom

* Wed Sep 18 2024 Southwest Research Institute <swri-robotics@swri.org> - 3.7.3-1
- Autogenerated by Bloom

* Mon Sep 16 2024 Southwest Research Institute <swri-robotics@swri.org> - 3.7.2-1
- Autogenerated by Bloom

* Fri Sep 06 2024 Southwest Research Institute <swri-robotics@swri.org> - 3.7.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 P. J. Reed <preed@swri.org> - 3.6.1-2
- Autogenerated by Bloom

