%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-swri-cli-tools
Version:        3.8.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS swri_cli_tools package

License:        BSD 3 Clause
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-natsort
Requires:       ros-kilted-marti-introspection-msgs
Requires:       ros-kilted-rcl-interfaces
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros2cli
Requires:       ros-kilted-ros2node
Requires:       ros-kilted-ros2param
Requires:       ros-kilted-ros2topic
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python3-natsort
BuildRequires:  ros-kilted-marti-introspection-msgs
BuildRequires:  ros-kilted-rcl-interfaces
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ros2cli
BuildRequires:  ros-kilted-ros2node
BuildRequires:  ros-kilted-ros2param
BuildRequires:  ros-kilted-ros2topic
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-copyright
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-pep257
BuildRequires:  ros-kilted-ament-xmllint
%endif

%description
Command line tools for introspecting ROS systems

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Thu Jun 26 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.5-1
- Autogenerated by Bloom

* Tue Jun 10 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.4-1
- Autogenerated by Bloom

* Tue Jun 03 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.3-1
- Autogenerated by Bloom

* Mon Jun 02 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.2-1
- Autogenerated by Bloom

* Thu May 29 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.1-1
- Autogenerated by Bloom

* Tue May 27 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.8.0-1
- Autogenerated by Bloom

* Tue May 20 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.5-1
- Autogenerated by Bloom

* Tue May 20 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.4-3
- Autogenerated by Bloom

* Tue Apr 22 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.4-2
- Autogenerated by Bloom

* Mon Apr 14 2025 Southwest Research Institute <swri-robotics@swri.org> - 3.7.4-1
- Autogenerated by Bloom

* Wed Sep 18 2024 Southwest Research Institute <swri-robotics@swri.org> - 3.7.3-1
- Autogenerated by Bloom

* Mon Sep 16 2024 Southwest Research Institute <swri-robotics@swri.org> - 3.7.2-1
- Autogenerated by Bloom

* Fri Sep 06 2024 Southwest Research Institute <swri-robotics@swri.org> - 3.7.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Southwest Research Institute <swri-robotics@swri.org> - 3.6.1-2
- Autogenerated by Bloom

