%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-swri-transform-util
Version:        3.5.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS swri_transform_util package

License:        BSD
URL:            https://github.com/swri-robotics/marti_common
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python%{python3_pkgversion}-devel
Requires:       geos-devel
Requires:       proj-devel
Requires:       python%{python3_pkgversion}-numpy
Requires:       ros-iron-cv-bridge
Requires:       ros-iron-diagnostic-msgs
Requires:       ros-iron-diagnostic-updater
Requires:       ros-iron-geographic-msgs
Requires:       ros-iron-geometry-msgs
Requires:       ros-iron-gps-msgs
Requires:       ros-iron-launch-xml
Requires:       ros-iron-marti-nav-msgs
Requires:       ros-iron-rcl-interfaces
Requires:       ros-iron-rclcpp
Requires:       ros-iron-rclcpp-components
Requires:       ros-iron-rclpy
Requires:       ros-iron-sensor-msgs
Requires:       ros-iron-swri-math-util
Requires:       ros-iron-swri-roscpp
Requires:       ros-iron-tf2
Requires:       ros-iron-tf2-geometry-msgs
Requires:       ros-iron-tf2-py
Requires:       ros-iron-tf2-ros
Requires:       yaml-cpp-devel
Requires:       ros-iron-ros-workspace
BuildRequires:  boost-devel
BuildRequires:  boost-python%{python3_pkgversion}-devel
BuildRequires:  geos-devel
BuildRequires:  pkgconfig
BuildRequires:  proj-devel
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ament-cmake-python
BuildRequires:  ros-iron-cv-bridge
BuildRequires:  ros-iron-diagnostic-msgs
BuildRequires:  ros-iron-diagnostic-updater
BuildRequires:  ros-iron-geographic-msgs
BuildRequires:  ros-iron-geometry-msgs
BuildRequires:  ros-iron-gps-msgs
BuildRequires:  ros-iron-marti-nav-msgs
BuildRequires:  ros-iron-rcl-interfaces
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-rclcpp-components
BuildRequires:  ros-iron-rclpy
BuildRequires:  ros-iron-sensor-msgs
BuildRequires:  ros-iron-swri-math-util
BuildRequires:  ros-iron-swri-roscpp
BuildRequires:  ros-iron-tf2
BuildRequires:  ros-iron-tf2-geometry-msgs
BuildRequires:  ros-iron-tf2-ros
BuildRequires:  yaml-cpp-devel
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The swri_transform_util package contains utility functions and classes for
transforming between coordinate frames.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Mon Aug 14 2023 P. J. Reed <preed@swri.org> - 3.5.4-1
- Autogenerated by Bloom

* Wed Jun 07 2023 P. J. Reed <preed@swri.org> - 3.5.3-1
- Autogenerated by Bloom

* Mon Jun 05 2023 P. J. Reed <preed@swri.org> - 3.5.2-1
- Autogenerated by Bloom

* Thu Apr 20 2023 P. J. Reed <preed@swri.org> - 3.5.0-3
- Autogenerated by Bloom

* Tue Mar 21 2023 P. J. Reed <preed@swri.org> - 3.5.0-2
- Autogenerated by Bloom

